### ISSUE TITLE
Resources are looked up outside of the project directory

### ISSUE THREAD

**Issue by anansii** [kobo/gaiden#36]
Edit: I'm sorry I didn't check the message again I removed the less/greater than symbols

After creating a simple project to play around with I was not able to get Gaiden to correctly use the default theme. The resource path inside the generated HTMLs points somewhere else:

"link rel="stylesheet" href="..\\..\\..\\..\\..\css\bootstrap.min.css"

instead of

"link rel="stylesheet" href="css\bootstrap.min.css"

I tried "gaiden clean/build" with a GVM managed version of Gaiden as well as "gaidenw". No difference.

**Comment by yamkazu** [comment]
Is that report complete? The generated HTML info appears to be disappearing.

**Comment by anansii** [comment]
Sorry, I fixed the original post.

**Comment by yamkazu** [comment]
We do not know the cause with just this information. Can you put a small project that reproduce the issue somewhere?

**Comment by anansii** [comment]
Sure.. I created another project like this:

PS D:\Gaiden> gaiden create-project test-theme
Created Gaiden project at D:\Gaiden\test-theme
PS D:\Gaiden> cd test-theme
PS D:\Gaiden\test-theme> gaiden install-theme default
Installed the theme at D:\Gaiden\test-theme\themes\default
PS D:\Gaiden\test-theme> gaiden build
Built document at file:///D:/Gaiden/test-theme/build/index.html
PS D:\Gaiden\test-theme>


The generated index.html again points somewhere wrong:
link rel="stylesheet" href="..\..\..\css\bootstrap.min.css"

**Comment by yamkazu** [comment]
Thanks your information. There was a problem in the handling of the absolute path on Windows.

Workaround on Gaiden 1.0:

Install Default theme.

```
$ gaiden install-theme default
```

Then remove the first '/' from the `resource` paths in `themes/default/layouts/main.html` as follows:

```
<html>
  <head>
    <meta charset="UTF-8">
    <% if (currentPage.title) { %>
    <title>${currentPage.numbers ? currentPage.numbers.join(".") + ". " : ""}${currentPage.title} - $title</title>
    <% } else { %>
    <title>$title</title>
    <% } %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="${resource('css/bootstrap.min.css')}">
    <link rel="stylesheet" href="${resource('css/font-awesome.min.css')}">
    <link rel="stylesheet" href="${resource('css/highlight.css')}">
    <link rel="stylesheet" href="${resource('css/style.css')}">
    <% extensionStyles.each { style -> %>
    <link rel="stylesheet" href="${style}">
    <% } %>
    <link rel="stylesheet" href="${resource('css/my.css')}">
  </head>
  <body>
    <div class="wrapper">
      ${include('header')}
      ${include('sidebar')}
      ${include('content')}
    </div>
    <script src="${resource('js/jquery-2.1.1.min.js')}"></script>
    <script src="${resource('js/highlight.js')}"></script>
    <script src="${resource('js/application.js')}"></script>
    <% extensionScripts.each { script -> %>
    <script src="${script}"></script>
    <% } %>
    <script src="${resource('js/my.js')}"></script>
    <% if (config.watch) { %>
    <script>
      if (window.WebSocket) {
        var socket = new WebSocket("ws://localhost:${config.serverPort}/");
        socket.onmessage = function () {
          location.reload();
        };
      }
    </script>
    <% } %>
  </body>
</html>
```
